'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbLubricentroEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbLubricentroEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property cliente() As DbSet(Of cliente)
    Public Overridable Property producto() As DbSet(Of producto)
    Public Overridable Property turno() As DbSet(Of turno)
    Public Overridable Property usuario() As DbSet(Of usuario)
    Public Overridable Property vehiculo() As DbSet(Of vehiculo)

End Class
