'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ventadetalle
    Public Property iddetalle As Integer
    Public Property idventa As Integer
    Public Property importe As Decimal
    Public Property idproducto As Integer
    Public Property cantidad As Integer
    Public Property precio As Decimal

    Public Overridable Property producto As producto
    Public Overridable Property ventacabecera As ventacabecera

End Class
